### ISSUE TITLE
`.add()` does not order the routes in a stable way

### ISSUE THREAD

**Issue by davazp** [troch/route-node#15]
Hi,

According to this comment in the `.add()` method:

https://github.com/troch/route-node/blob/master/modules/RouteNode.js#L111-L142

the order of the routes should be preserved if they are equivalent under all the conditions (same length of the last segment) and so on. However, it uses the `sort` method of an array, which does not ensure the sort is stable:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort

We found a weird issue where the order of the routes swapped two routes each time a new route was added to the router.

Please, let's add extra conditions to avoid returning 0 from the sort callback!

Thanks!

**Comment by davazp** [comment]
Perhaps replace sort with a stable sort like the one implemented at

https://stackoverflow.com/questions/1427608/fast-stable-sorting-algorithm-implementation-in-javascript

?

**Comment by troch** [comment]
Is your issue with more than 10 child routes in Chrome (V8)?

**Comment by davazp** [comment]
Yes, I have more than 10 routes and V8 (but on NodeJS).

**Comment by troch** [comment]
Sort is unstable on V8 for arrays with more than 10 items. Can you make a PR to not return 0 and instead return the index difference?
