### ISSUE TITLE
Warning still relevant?

### ISSUE THREAD

**Issue by pluma** [troch/route-node#2]
router5 seems to be beyond "being developed" as it's at 3.x now and this module is at 1.x indicating the API will be relatively stable.

Is the warning that the API will change without notice still relevant and necessary? I'm considering using route-node directly instead of router5 and the warning makes that seem like a really bad idea.

**Comment by troch** [comment]
No the warning is not relevant any more, and I follow semver guidelines. I'm removing it.

**Comment by pluma** [comment]
Awesome! Thanks.
