### ISSUE TITLE
The buildPathFromSegments function is not respecting queryParams options

### ISSUE THREAD

**Issue by chibihoho** [troch/route-node#21]
```javascript
const searchPart = build(searchParamsObject)
```
It looks like the queryParams options are not being passed in here leading to the default options always being used. Is this on purpose? Is there a way to make this function use the queryParams options initialized with the router?

**Comment by troch** [comment]
Hey @chibihoho, thanks for raising this issue. It has now been fixed and released (v3.1.1). If you are using router5, patch is going to be released now.
