### ISSUE TITLE
Deeply nested '/' path doesn't work without optional parameters

### ISSUE THREAD

**Issue by klimashkin** [troch/route-node#5]
```
{
  name: 'app', path: '?:showVersion', children: [
    {name: 'admin', path: '/admin', children: [
      {name: 'users', path: '/?:sort?:page'},
    ]},
}
```
If urls is `/admin/?page=1` `transitionPath(...).toActivate` returns 
`['app', 'app.admin', 'app.admin.users']`

But if url is `/admin/` `transitionPath(...).toActivate` returns only 
`['app', 'app.admin']`

(`strictQueryParams : false`)

**Comment by troch** [comment]
Fixed with version 1.5.1, router5 updated to v4.2.2
